### ISSUE TITLE
메인 화면에 어떤 방식으로든 질문을 하나 띄운다

### ISSUE THREAD

**Issue by hyunjuuun** [organization-hyun/moondab#4]
* [x] 백엔드 통신 없이 메인 화면에 질문을 띄운다.

**Comment by Hg-lab** [comment]
Flutter 참고 Repo

- https://github.com/LiiNen/vocalist-app/
- https://github.com/Kimhanyeol/abc_money_diary/
- https://github.com/codemakim/doit_everyday

**Comment by Hg-lab** [comment]
Kotlin + Spring 프로젝트
https://github.com/FrenchRuin/issue-service
